require("plugin-config/vscode")
require("plugin-config/bufferline")
require("plugin-config/nvimtree")
require("plugin-config/dashboard")
require("plugin-config/lualine")
require("plugin-config/whichkey")
require('plugin-config/terminal')
require('plugin-config/coderunner')
require('plugin-config/telescope')
require('plugin-config/autosession')
require('plugin-config/treesitter')
require('plugin-config/markdown')
require('plugin-config/img-paste')
require('plugin-config/nerdcommenter')
require('plugin-config/auto-pairs')
require('plugin-config/coc')
require('plugin-config/translator')

-- require('lsp/setup')
-- require('plugin-config/cmp')
